name: snapfake
description: A clone of Snapchat

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bordered_text: ^1.0.0
  camera:
  path_provider:
  path:
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0
  cloud_firestore: ^0.14.0
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/